ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE; 

-- 사용자 생성
CREATE USER GGANGPAE1
IDENTIFIED BY TJOEUN;

-- 권한 부여
GRANT CONNECT, RESOURCE TO GGANGPAE1;

-- 시스템 권한 확인
SELECT *
FROM SYSTEM_PRIVILEGE_MAP;

-- ROLE 생성 권한 부여
GRANT CREATE ROLE TO GGANGPAE1;

-- ROLE 생성 권한 취소
REVOKE CREATE ROLE FROM GGANGPAE1;

-- Object 권한 확인
SELECT *
FROM TABLE_PRIVILEGE_MAP;

-- GGANGPAE1 사용자에게 SCOTT이 소유하고 있는 EMP 테이블을 조회하고 삽입할 수 있는 권한을 부여
GRANT CREATE SESSION TO GGANGPAE1;

GRANT SELECT, INSERT ON EMP TO GGANGPAE1;

SELECT EMPNO, ENAME, JOB, HIREDATE, SAL
FROM SCOTT.EMP
WHERE DEPTNO = 10;

-- EMP 테이블에 부여한 SELECT권한을 GGANGPAE1 에게서 취소
REVOKE SELECT ON EMP 
FROM GGANGPAE1;

conn GGANGPAE1/TJOEUN;

SELECT *
FROM scott.EMP;

-- SCOTT에게 할당되어 있는 SYSTEM ROLE을 확인
SELECT *
FROM ROLE_SYS_PRIVS;

-- LEVEL1이라는 ROLE을 생성
CREATE ROLE LEVEL1;

-- LEVEL1이라는 ROLE에 CREATE SESSION,CREATE TABLE,CREATE VIEW 의 권한을 부여
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW
TO LEVEL1;

-- TEST1/TIGER1과 TEST2/TIGER2라는 사용자를 생성
CREATE USER TEST1
IDENTIFIED BY TIGER1;

CREATE USER TEST2
IDENTIFIED BY TIGER2;

-- TEST1,TEST2에 LEVEL1이라는 ROLE를 부여
GRANT LEVEL1 
TO TEST1, TEST2;

-- 연습문제
CREATE USER IRIN
IDENTIFIED BY SM;

GRANT CONNECT, RESOURCE 
TO IRIN;

REVOKE CONNECT, RESOURCE 
FROM IRIN;

DROP USER IRIN;