-- 데이터 삽입
DROP TABLE DEPT01;

CREATE TABLE DEPT01
	AS SELECT * FROM DEPT WHERE 1=0;

INSERT INTO DEPT01(DEPTNO, DNAME, LOC)
VALUES(10, 'ACCOUNTING', 'NEW YORK');

INSERT INTO DEPT01 
(DEPTNO, DNAME, LOC) 
VALUES (10, 'ACCOUNTING'); 

INSERT INTO DEPT01 
(DEPTNO, DNAME, LOC) 
VALUES(10, 'ACCOUNTING', 'NEW YORK', 20);

INSERT INTO DEPT01 
(NUM, DNAME, LOC) 
VALUES(10, 'ACCOUNTING', 'NEW YORK'); 

INSERT INTO DEPT01 
(DEPTNO, DNAME, LOC) 
VALUES(10, ACCOUNTING, 'NEW YORK'); 

-- 컬럼 이름을 생략한 데이터 삽입
INSERT INTO DEPT01 
VALUES (20, 'RESEARCH', 'DALLAS'); 


CREATE TABLE SAM01
	AS SELECT EMPNO, ENAME, JOB, SAL FROM EMP WHERE 1=0;
	
INSERT INTO SAM01(EMPNO, ENAME, JOB, SAL) 
VALUES (1000, 'APPLE', 'POLICE', 10000); 

INSERT INTO SAM01(EMPNO, ENAME, JOB, SAL) 
VALUES (1010, 'BANANA', 'NURSE', 15000); 

INSERT INTO SAM01
VALUES (1020, 'ORANGE', 'DOCTOR', 25000); 

SELECT *
FROM SAM01;

-- NULL 삽입
DESC DEPT;

INSERT INTO DEPT01 
(DEPTNO, DNAME) 
VALUES (30, 'SALES');

INSERT INTO DEPT01 
VALUES (40, 'OPERATIONS', NULL); 

INSERT INTO DEPT01 
VALUES (50, '', 'CHICAGO'); 

SELECT *
FROM DEPT01;

INSERT INTO SAM01(EMPNO, ENAME, SAL)
VALUES(1030, 'VERY', 25000);

INSERT INTO SAM01
VALUES(1040, 'CAT', '', 2000);

SELECT *
FROM SAM01;

-- 서브쿼리를 이용한 데이터 삽입
DROP TABLE DEPT02;

CREATE TABLE DEPT02
AS 
SELECT * FROM DEPT WHERE 1=0;

INSERT INTO DEPT02
SELECT * FROM DEPT;

SELECT *
FROM DEPT02;

INSERT INTO SAM01
SELECT EMPNO, ENAME, JOB, SAL 
FROM EMP
WHERE DEPTNO = 10;

SELECT *
FROM SAM01;

-- 다중 테이블에 데이터 입력
CREATE TABLE EMP_HIR
AS
SELECT EMPNO, ENAME, HIREDATE
FROM EMP
WHERE 0 = 1;

CREATE TABLE EMP_MGR
AS
SELECT EMPNO, ENAME, MGR
FROM EMP
WHERE 0 = 1;

INSERT ALL 
INTO EMP_HIR VALUES(EMPNO, ENAME, HIREDATE)
INTO EMP_MGR VALUES(EMPNO, ENAME, MGR)
SELECT EMPNO, ENAME, HIREDATE, MGR 
FROM EMP
WHERE DEPTNO=20;

SELECT *
FROM EMP_HIR;

SELECT *
FROM EMP_MGR;

CREATE TABLE EMP_HIR02
AS
SELECT EMPNO, ENAME, HIREDATE
FROM EMP
WHERE 0=1;

CREATE TABLE EMP_SAL
AS
SELECT EMPNO, ENAME, SAL
FROM EMP
WHERE 0=1;

INSERT ALL 
WHEN HIREDATE > '1982/01/01' THEN
INTO EMP_HIR02 VALUES(EMPNO, ENAME, HIREDATE)
WHEN SAL > 2000 THEN
INTO EMP_SAL VALUES(EMPNO, ENAME, SAL)
SELECT EMPNO, ENAME, HIREDATE, SAL 
FROM EMP;

SELECT *
FROM EMP_HIR02;

SELECT *
FROM EMP_SAL;


CREATE TABLE SALES( 
SALES_ID NUMBER(4),
WEEK_ID NUMBER(4),
MON_SALES NUMBER(8, 2),
TUE_SALES NUMBER(8, 2),
WED_SALES NUMBER(8, 2),
THU_SALES NUMBER(8, 2),
FRI_SALES NUMBER(8, 2));

CREATE TABLE SALES_DATA( 
SALES_ID NUMBER(4),
WEEK_ID NUMBER(4),
DAILY_ID NUMBER(4), 
SALES NUMBER(8, 2));

INSERT INTO SALES VALUES 
(1001, 1, 200, 100, 300, 400, 500);

INSERT INTO SALES VALUES 
(1002, 2, 100, 300, 200, 500, 350);

INSERT ALL
INTO SALES_DATA VALUES(SALES_ID, WEEK_ID, 1, MON_SALES)
INTO SALES_DATA VALUES(SALES_ID, WEEK_ID, 2, TUE_SALES)
INTO SALES_DATA VALUES(SALES_ID, WEEK_ID, 3, WED_SALES)
INTO SALES_DATA VALUES(SALES_ID, WEEK_ID, 4, THU_SALES)
INTO SALES_DATA VALUES(SALES_ID, WEEK_ID, 5, FRI_SALES)
SELECT SALES_ID, WEEK_ID, MON_SALES, TUE_SALES, WED_SALES,
THU_SALES, FRI_SALES 
FROM SALES;

SELECT *
FROM SALES;

-- 데이터 수정
DROP TABLE EMP01;

CREATE TABLE EMP01
AS
SELECT *
FROM EMP;

UPDATE EMP01
SET DEPTNO=30; 

UPDATE EMP01
SET SAL = SAL * 1.1;

UPDATE EMP01
SET HIREDATE = SYSDATE;

SELECT *
FROM EMP01;

-- 특정 행만 데이터 수정
DROP TABLE EMP01;

CREATE TABLE EMP01
AS
SELECT *
FROM EMP;

UPDATE EMP01
SET DEPTNO=30
WHERE DEPTNO=10;

UPDATE EMP01
SET SAL = SAL * 1.1 
WHERE SAL >= 3000;

UPDATE EMP01
SET HIREDATE = SYSDATE
WHERE SUBSTR(HIREDATE, 1, 2)='82';

SELECT *
FROM EMP01;


UPDATE SAM01
SET SAL = SAL - 5000
WHERE SAL >= 10000;

SELECT *
FROM SAM01;

-- 2개 이상의 컬럼 수정
UPDATE EMP01
SET DEPTNO=20, JOB='MANAGER'
WHERE ENAME='SCOTT'; 

UPDATE EMP01
SET HIREDATE = SYSDATE, SAL=50, COMM=4000
WHERE ENAME='SCOTT'; 

-- 서브쿼리로 수정
UPDATE DEPT01
SET LOC=(SELECT LOC 
	FROM DEPT01 
	WHERE DEPTNO=40)
	WHERE DEPTNO=20;

CREATE TABLE SAM02
AS
SELECT ENAME, SAL, HIREDATE, DEPTNO
FROM EMP;

UPDATE SAM02 
SET SAL = SAL + 1000
WHERE DEPTNO = (SELECT DEPTNO 
				FROM DEPT
				WHERE LOC = 'DALLAS');

SELECT * 
FROM SAM02;

UPDATE DEPT01
SET (DNAME, LOC)=(SELECT DNAME, LOC
                  FROM DEPT
                  WHERE DEPTNO=40)
WHERE DEPTNO=20;

UPDATE SAM02
SET (SAL, HIREDATE)=(SELECT SAL, HIREDATE
                  FROM EMP
                  WHERE ENAME='KING');
                 
SELECT *
FROM SAM02;


-- 데이터 삭제
DROP TABLE DEPT01;

CREATE TABLE DEPT01 
AS
SELECT *
FROM DEPT;

DELETE FROM DEPT01;

SELECT * FROM DEPT01;

DROP TABLE DEPT01;

CREATE TABLE DEPT01 
AS
SELECT *
FROM DEPT;

DELETE FROM DEPT01
WHERE DEPTNO=30;

DELETE FROM SAM01 
WHERE JOB IS NULL;

SELECT *
FROM SAM01;

DELETE FROM EMP01
WHERE DEPTNO=(SELECT DEPTNO
              FROM DEPT
              WHERE DNAME='SALES');
             
DELETE FROM SAM02
WHERE DEPTNO = (SELECT DEPTNO
              	FROM DEPT
              	WHERE DNAME='RESEARCH');
              
-- MERGE
DROP TABLE EMP01;

CREATE TABLE EMP01
AS
SELECT *
FROM EMP;

SELECT *
FROM EMP01;

DROP TABLE EMP02;

CREATE TABLE EMP02
AS
SELECT * FROM EMP
WHERE JOB='MANAGER';

UPDATE EMP02
SET JOB='TEST';

INSERT INTO EMP02
VALUES(8000, 'SYJ', 'TOP', 7566, '2009/01/12', 1200, 10, 20);

MERGE INTO EMP01
USING EMP02
ON(EMP01.EMPNO=EMP02.EMPNO)
WHEN MATCHED THEN
UPDATE SET
EMP01.ENAME=EMP02.ENAME,
EMP01.JOB=EMP02.JOB,
EMP01.MGR=EMP02.MGR,
EMP01.HIREDATE=EMP02.HIREDATE,
EMP01.SAL=EMP02.SAL,
EMP01.COMM=EMP02.COMM,
EMP01.DEPTNO=EMP02.DEPTNO
WHEN NOT MATCHED THEN
INSERT VALUES(EMP02.EMPNO, EMP02.ENAME, EMP02.JOB, 
EMP02.MGR, EMP02.HIREDATE, EMP02.SAL, 
EMP02.COMM, EMP02.DEPTNO);

============================

CREATE TABLE MY_DATA
(ID NUMBER(4) NOT NULL,
 NAME VARCHAR2(10),
 USERID VARCHAR2(30),
 SALARY NUMBER(10,2));

INSERT INTO MY_DATA VALUES(1, 'Scott', 'sscott', 10000);
INSERT INTO MY_DATA VALUES(2, 'Ford', 'fford', 13000);
INSERT INTO MY_DATA VALUES(3, 'Patel', 'ppatel', 33000);
INSERT INTO MY_DATA VALUES(4, 'Report', 'rreport', 23500);
INSERT INTO MY_DATA VALUES(5, 'Good', 'ggood', 44450);

SELECT *
FROM MY_DATA;

UPDATE MY_DATA
SET SALARY = 65000
WHERE ID = 3;

DELETE FROM MY_DATA
WHERE NAME='Ford';

UPDATE MY_DATA
SET SALARY = 15000
WHERE SALARY <= 15000;

DROP TABLE MY_DATA;