-- EMP 테이블에서 SAL의 합계 조회
SELECT SUM(SAL) 
FROM EMP;

-- EMP 테이블에서 COMM의 합계 구하기
SELECT SUM(COMM) 
FROM EMP;

-- EMP 테이블에서 SAL의 평균 구하기
SELECT AVG(SAL) 
FROM EMP;

-- 가장 높은 급여와 가장 낮은 급여를 구하기
SELECT MAX(SAL), MIN(SAL)
FROM EMP;

-- 가장 급여가 높은 값 구하기
SELECT MAX(SAL)
FROM EMP;

-- 급여가 가장 높은 값 과 사원 이름 구하기 - 에러
SELECT ENAME,MAX(SAL)
FROM EMP;

SELECT MIN(HIREDATE) 입사일, MAX(HIREDATE) 입사일
FROM EMP;


-- 사원 테이블의 사원들 중에서 커미션을 받은 사원의 수를 구하는 예제
SELECT COUNT(COMM) 
FROM EMP; 

-- 전체 사원의 수와 커미션을 받는 사원의 수를 구하는 예제
SELECT COUNT(*), COUNT(COMM) 
FROM EMP;

SELECT COUNT(*) AS 사원수
FROM EMP
WHERE DEPTNO = 10 AND COMM IS NULL;

-- 업무의 개수 구하기
SELECT COUNT(JOB) 업무수
FROM EMP;

SELECT COUNT(DISTINCT JOB) 업무수
FROM EMP;

-- 사원 테이블을 부서 번호로 그룹화 해서 출력
SELECT DEPTNO 
FROM EMP 
GROUP BY DEPTNO;

-- 부서별 평균 급여
SELECT DEPTNO, AVG(SAL)
FROM EMP
GROUP BY DEPTNO;

-- EMP 테이블에서 소속 부서별(DEPTNO) 최대 급여(SAL)와 최소 급여를 출력
SELECT DEPTNO, MAX(SAL), MIN(SAL)
FROM EMP 
GROUP BY DEPTNO;

-- 부서별(DEPTNO)로 사원 수와 커미션(COMM)을 받는 사원들의 수를 계산
SELECT DEPTNO, COUNT(*), COUNT(COMM)
FROM EMP 
GROUP BY DEPTNO;

-- 부서 와 직무(DEPTNO, JOB)별로 사원 수와 급여(SAL)의 합을 계산
SELECT DEPTNO, JOB,  COUNT(*), SUM(SAL)
FROM EMP 
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO, JOB;

-- 부서별 평균 급여(SAL)가 가장 큰 값 조회
SELECT MAX(AVG(SAL))
FROM EMP 
GROUP BY DEPTNO;

-- HAVING
-- 부서별로 그룹화 한 후(GROUP BY), 그룹 지어진 부서별 평균 급여가 2000 이상인(HAVING) 부서번호와 부서별 평균 급여를 출력하는 경우
SELECT DEPTNO, ROUND(AVG(SAL)) 
FROM EMP
GROUP BY DEPTNO
HAVING AVG(SAL) >= 2000;

-- 부서의 최대 급여 와 최소 급여를 구하되 최대 급여가 2900이상인 부서만 출력 
SELECT DEPTNO, MAX(SAL), MIN(SAL) 
FROM EMP
GROUP BY DEPTNO
HAVING MAX(SAL) >= 2900;

-- EMP 테이블에서 DEPTNO가 10, 20인 부서의 SAL의 평균을 구하기
SELECT DEPTNO, AVG(SAL)
FROM EMP 
GROUP BY DEPTNO
HAVING DEPTNO IN (10,20);

SELECT DEPTNO, AVG(SAL)
FROM EMP 
WHERE DEPTNO IN(10,20)
GROUP BY DEPTNO;

---------------------------------------------------

SELECT COUNT(ENAME), MAX(SAL), MIN(SAL), SUM(SAL) 
FROM EMP;

SELECT JOB, MAX(SAL), MIN(SAL), SUM(SAL) 
FROM EMP 
GROUP BY JOB;

SELECT JOB, COUNT(JOB) 
FROM EMP 
GROUP BY JOB;

SELECT MAX(SAL), MIN(SAL), MAX(SAL)-MIN(SAL) 
FROM EMP;

SELECT TO_CHAR(HIREDATE, 'YY') "H_YEAR", COUNT(*), MIN(SAL), MAX(SAL), AVG(SAL), SUM(SAL) 
FROM EMP 
GROUP BY TO_CHAR(HIREDATE,'YY')
ORDER BY TO_CHAR(HIREDATE,'YY') ASC;

SELECT COUNT(HIREDATE) TOTAL, 
	COUNT(DECODE(TO_CHAR(HIREDATE,'YYYY'),1980,0)) "1980",
	COUNT(DECODE(TO_CHAR(HIREDATE,'YYYY'),1981,0))"1981",
	COUNT(DECODE(TO_CHAR(HIREDATE,'YYYY'),1982,0))"1982",
	COUNT(DECODE(TO_CHAR(HIREDATE,'YYYY'),1987,0))"1987" 
FROM EMP;

SELECT JOB, 
	SUM(DECODE(DEPTNO,10,SAL)) "10",
	SUM(DECODE(DEPTNO,20,SAL)) "20",
	SUM(DECODE(DEPTNO,30,SAL)) "30", SUM(SAL) TOTAL
FROM EMP 
GROUP BY JOB 
ORDER BY JOB ASC;