-- DUAL 테이블
DESC DUAL;

SELECT * 
FROM DUAL;

SELECT 60 * 60 * 24 
FROM DUAL;

SELECT SYSDATE , SYSTIMESTAMP 
FROM DUAL;

-- 수치 함수

-- 10 에 대한 절대값
SELECT -10, ABS(-10)
FROM DUAL;

-- 소수 버리기
SELECT   34.5678,  FLOOR(34.5678)
FROM DUAL;

-- 소수 올림
SELECT   34.5678,  CEIL(34.5678)
FROM DUAL;

-- 반올림
SELECT 34.5678, ROUND(34.5678)
FROM DUAL;

SELECT 34.5678, ROUND(34.5678, 2)
FROM DUAL;

SELECT 34.5678, ROUND(34.5678, -1)
FROM DUAL;

-- 버림
SELECT TRUNC(34.5678, 2), TRUNC(34.5678, -1), TRUNC(34.5678)
FROM DUAL;

-- 나머지
SELECT MOD(27, 2), MOD(27, 5), MOD(27, 7) 
FROM DUAL;

SELECT *
FROM EMP
WHERE MOD(EMPNO, 2) = 1;

-- 문자 함수

-- 대문자로 변환
SELECT 'Welcome to Oracle', UPPER('Welcome to Oracle')
FROM DUAL;

-- 소문자로 변환
SELECT 'WELCOME TO ORACLE', LOWER('WELCOME TO ORACLE')
FROM DUAL;

-- 첫글자만 대문자로 변환
SELECT 'WELCOME TO ORACLE', INITCAP('WELCOME TO ORACLE')
FROM DUAL;

SELECT EMPNO, ENAME, JOB 
FROM EMP 
WHERE JOB='manager';

SELECT EMPNO, ENAME, JOB
FROM EMP
WHERE LOWER(JOB) ='manager';

-- 글자 수
SELECT LENGTH('ORACLE'), LENGTH('오라클')
FROM DUAL;

-- 바이트 수
SELECT LENGTHB('ORACLE'), LENGTHB('오라클')
FROM DUAL;

-- 문자열 자르기
SELECT SUBSTR('WELCOME TO ORACLE', 4, 3)
FROM DUAL;

SELECT SUBSTR('WELCOME TO ORACLE', -4, 3) 
FROM DUAL;

SELECT SUBSTR(HIREDATE, 1, 2) 년도, SUBSTR(HIREDATE, 4, 2) 달
FROM EMP;

SELECT *
FROM EMP
WHERE SUBSTR(HIREDATE, 4, 2)='12';

SELECT *
FROM EMP
WHERE SUBSTR(HIREDATE, 1, 2) = '81'; 

SELECT *
FROM EMP
WHERE SUBSTR(ENAME, -1, 1) ='E';

SELECT SUBSTR('WELCOME TO ORACLE', 3, 4), SUBSTRB('WELCOME TO ORACLE', 3, 4)
FROM DUAL;

SELECT SUBSTR('웰컴투오라클', 3, 4), SUBSTRB('웰컴투오라클', 3, 4)
FROM DUAL;

-- 문자 검색
SELECT INSTR('WELCOME TO ORACLE', 'O')
FROM DUAL;

SELECT INSTR('WELCOME TO ORACLE', 'O', 6, 2)
FROM DUAL;

SELECT INSTR('데이터베이스', '이', 3, 1), INSTRB('데이터베이스', '이', 3, 1)
FROM DUAL;

SELECT *
FROM EMP
WHERE INSTR(ENAME, 'N') = 3;

-- 문자 채우기
SELECT LPAD('ORACLE', 20, '#')
FROM DUAL;

SELECT RPAD('ORACLE', 20, '#')
FROM DUAL;

-- 공백 및 문자 제거 
SELECT LTRIM(' ORACLE ') 
FROM DUAL;

SELECT RTRIM(' ORACLE ') 
FROM DUAL;

SELECT TRIM(' ORACLE ') 
FROM DUAL;

SELECT TRIM('A' FROM 'AAAAORACLEAAAA') 
FROM DUAL;

-- 문자열 결합
SELECT CONCAT('ORACLE', 'JAVA')
FROM DUAL;

-- 인코딩 변환
SELECT CONVERT('Ä Ê Í Ó Ø A B C D E ', 'UTF8', 'WE8ISO8859P1') 
FROM DUAL;



-- 날짜 함수
-- 현재 시간
SELECT SYSDATE
FROM DUAL;

-- 날짜 연산
SELECT SYSDATE-1 어제, SYSDATE 오늘, SYSDATE+1 내일
FROM DUAL;

-- 반올림
SELECT ROUND(SYSDATE-HIREDATE)  근무일수
FROM EMP;

SELECT HIREDATE, ROUND (HIREDATE, 'MONTH') 
FROM EMP;

-- 버림
SELECT HIREDATE, TRUNC(HIREDATE, 'MONTH')
FROM EMP;

-- 날짜 연산
SELECT MONTHS_BETWEEN(SYSDATE, HIREDATE) AS "근무한 개월수"
FROM EMP;

SELECT ADD_MONTHS(SYSDATE, 6) AS "6개월 후 날짜"
FROM DUAL;

SELECT NEXT_DAY(SYSDATE, '토요일') AS "다음 주 토요일" , LAST_DAY(SYSDATE) AS "이번 달 마지막 날"
FROM DUAL;

-- 형 변환 함수
-- 날짜를 문자열로 변환
SELECT SYSDATE, TO_CHAR(SYSDATE, 'YYYY-MM-DD')
FROM DUAL;

SELECT HIREDATE, TO_CHAR (HIREDATE, 'YYYY/MM/DD DAY') 
FROM EMP;

SELECT HIREDATE, TO_CHAR (HIREDATE, 'YY/MON/DD DY') 
FROM EMP;

SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD, HH24:MI:SS')
FROM DUAL;

-- 숫자를 문자열로 변환
SELECT TO_CHAR(1230000) 
FROM DUAL;

SELECT ENAME, SAL, TO_CHAR (SAL, 'L999,999') 
FROM EMP;

SELECT TO_CHAR (123456, '000000000'), 
       TO_CHAR (123456, '999,999,999') 
FROM DUAL;

-- 문자열을 날짜로 변환
SELECT ENAME, HIREDATE FROM EMP
WHERE HIREDATE=TO_DATE(19810220,'YYYYMMDD')

-- 날짜 차이
SELECT TRUNC(SYSDATE-TO_DATE('1987/05/05', 'YYYY/MM/DD'))
FROM DUAL;

-- 문자를 숫자로 변환
SELECT TO_NUMBER('20,000', '99,999') - TO_NUMBER('10,000', '99,999')
FROM DUAL;

-- 암시적 형변환
SELECT *
FROM EMP
WHERE EMPNO = 7788;

SELECT *
FROM EMP
WHERE EMPNO = '7788';

SELECT *
FROM EMP
WHERE EMPNO = TO_NUMBER('7788');


-- NULL 관련 함수
SELECT ENAME, SAL, COMM, SAL*12+COMM, 
  NVL(COMM, 0), SAL*12+NVL(COMM, 0)
FROM EMP
ORDER BY JOB;


SELECT ENAME, SAL, COMM, SAL*12+COMM, 
  NVL2(COMM,SAL*12+COMM, SAL*12)
FROM EMP
ORDER BY JOB;


SELECT NULLIF('KOREA','KOREA'), NULLIF('KOREA','KOREA')
FROM DUAL;

-- COMM이 NULL이 아니면 COMM을 그렇지 않으면 SAL을 SAL이 NULL이면 0으로 출력
SELECT ENAME, SAL, COMM, COALESCE(COMM, SAL,0)
FROM EMP;

-- 부서번호에 해당되는 부서명을 구하기
SELECT ENAME, DEPTNO, 
              DECODE(DEPTNO,  10, 'ACCOUNTING', 
                              20, 'RESEARCH', 
                              30, 'SALES', 
                              40, 'OPERATIONS' ) 
               AS DNAME
FROM EMP;

SELECT EMPNO, ENAME, JOB, SAL, DECODE(JOB, 'ANALYST', SAL * 1.05,
										   'SALESMAN', SAL * 1.1,
										   'MANAGER', SAL * 1.15,
										   'CLERK', SAL * 1.2,
										   SAL) AS UPSAL
FROM EMP;


SELECT ENAME, DEPTNO,
              CASE WHEN DEPTNO=10 THEN 'ACCOUNTING' 
                        WHEN DEPTNO=20 THEN 'RESEARCH' 
                        WHEN DEPTNO=30 THEN 'SALES' 
                        WHEN DEPTNO=40 THEN 'OPERATIONS'
               END AS DNAME
FROM EMP;

-------------------------------------------

SELECT SYSDATE "CURRENT_DATE" 
FROM DUAL;

SELECT *
FROM EMP
WHERE SUBSTR(HIREDATE, 4, 2) = '09';

SELECT ENAME,HIREDATE,ADD_MONTHS(HIREDATE,5)
FROM EMP;

SELECT ENAME, HIREDATE, MONTHS_BETWEEN(SYSDATE, HIREDATE), 
	SAL*MONTHS_BETWEEN(SYSDATE, HIREDATE) 
FROM EMP;

SELECT ENAME ||' EARNS'||TO_CHAR(SAL,'$999,999')||' MONTHLY BUT WANTS'||
	TO_CHAR(SAL*3,'$999,999')"DREAM SALARY" 
FROM EMP;

SELECT LPAD(ENAME || SAL, 15, '*') 
FROM EMP;

SELECT ENAME, JOB, HIREDATE, TO_CHAR(HIREDATE, 'DAY') 
FROM EMP;

SELECT ENAME, LENGTH(ENAME), JOB 
FROM EMP 
WHERE LENGTH(ENAME) >= 6;

SELECT ENAME, JOB, SAL, NVL(COMM,0) COMM, SAL+NVL(COMM,0) 
FROM EMP ;
