ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE USER scott IDENTIFIED BY tiger;

ALTER USER scott DEFAULT TABLESPACE USERS;

ALTER USER scott TEMPORARY TABLESPACE TEMP;

GRANT CONNECT, DBA, RESOURCE to scott; 