-- 시작값이 10이고 10씩 증가하는 SEQUENCE EMP_SEQ
CREATE SEQUENCE EMP_SEQ
INCREMENT BY 10
START WITH 10;

-- NEXTVAL로 새로운 값을 생성
SELECT EMP_SEQ.NEXTVAL 
FROM DUAL;

-- SEQUENCE의 현재 값을 알아내기 위해서 CURRVAL를 사용
SELECT EMP_SEQ.CURRVAL 
FROM DUAL;


-- 시작값이 1이고 1씩 증가하고 최댓값이 100000이 되는 SEQUENCE EMP_PK_SEQ
CREATE SEQUENCE EMP_PK_SEQ
START WITH 1 
INCREMENT BY 1 
MAXVALUE 100000 ; 

DROP TABLE EMP01;

CREATE TABLE EMP01(
	EMPNO NUMBER(4) PRIMARY KEY,
	ENAME VARCHAR(10),
	HIREDATE DATE
);

INSERT INTO EMP01
VALUES(EMP_PK_SEQ.NEXTVAL, 'JULIA' , SYSDATE); 

SELECT *
FROM EMP01;

-- 시퀀스 삭제
DROP SEQUENCE EMP_SEQ;

-- 시퀀스 생성
CREATE SEQUENCE DEPT_DEPTNO_SEQ
START WITH 10
INCREMENT BY 10 
MAXVALUE 30; 


----------- 연습문제
CREATE SEQUENCE TEST_SEQ
START WITH 1
INCREMENT BY 1 
MAXVALUE 999999; 

SELECT *
FROM USER_SEQUENCES;

SELECT TEST_SEQ.NEXTVAL 
FROM DUAL;

SELECT TEST_SEQ.CURRVAL 
FROM DUAL;

DROP SEQUENCE TEST_SEQ;

CREATE TABLE DEPT_EXAMPLE(
	DEPTNO NUMBER(4) PRIMARY KEY,
	DNAME VARCHAR(15),
	LOC VARCHAR(15));

CREATE SEQUENCE DEPT_EXAMPLE_SEQ
START WITH 10
INCREMENT BY 10; 

INSERT  INTO DEPT_EXAMPLE(DEPTNO, DNAME, LOC)
VALUES(DEPT_EXAMPLE_SEQ.NEXTVAL, '인사과', '서울');

INSERT  INTO DEPT_EXAMPLE(DEPTNO, DNAME, LOC)
VALUES(DEPT_EXAMPLE_SEQ.NEXTVAL, '경리과', '서울');

INSERT  INTO DEPT_EXAMPLE(DEPTNO, DNAME, LOC)
VALUES(DEPT_EXAMPLE_SEQ.NEXTVAL, '총무과', '대전');

INSERT  INTO DEPT_EXAMPLE(DEPTNO, DNAME, LOC)
VALUES(DEPT_EXAMPLE_SEQ.NEXTVAL, '기술팀', '인천');

SELECT *
FROM DEPT_EXAMPLE ;
