-- 조회 구문
SELECT * 
FROM EMP;

-- 실행 계획 확인
CREATE INDEX JOB ON EMP(JOB);

CREATE INDEX SAL ON EMP(SAL);

SELECT  ENAME
  FROM EMP
 WHERE JOB='SALESMAN'
  AND SAL BETWEEN 3000 AND 6000;
  
 -- 규칙 기반으로 SQL 실행
 SELECT ROWID
 FROM EMP;

SELECT /*+ RULE */ *
FROM EMP
WHERE ROWID = 'AAAR+xAAHAAAACTAAA';

-- USER_IND_COLUMNS 데이터 딕셔너리 뷰로 인덱스의 생성 유무를 확인
SELECT INDEX_NAME, TABLE_NAME , COLUMN_NAME
FROM USER_IND_COLUMNS
WHERE TABLE_NAME IN('EMP', 'DEPT'); 

-- 인덱스 생성
CREATE INDEX IDX_EMP_ENAME
ON EMP(ENAME);

-- 인덱스 삭제
DROP INDEX IDX_EMP_ENAME;

-- 결합 인덱스
CREATE INDEX IDX_DEPT_COM
ON DEPT(DEPTNO, DNAME);

SELECT INDEX_NAME, COLUMN_NAME
FROM USER_IND_COLUMNS
WHERE TABLE_NAME = 'DEPT';

-- 함수 기반 인덱스
CREATE INDEX IDX_EMP_ANNSAL
ON EMP(SAL*12);

SELECT INDEX_NAME, COLUMN_NAME
FROM USER_IND_COLUMNS
WHERE TABLE_NAME = 'EMP';

-- nested loop join
SELECT /*+  use_nl(d) */ *
FROM EMP e, DEPT d
WHERE e.DEPTNO = d.DEPTNO AND e.DEPTNO = 10;

-- sort merge join 
SELECT /*+ ordered use_merge(d) */ *
FROM EMP e, DEPT d
WHERE e.DEPTNO = d.DEPTNO AND e.DEPTNO = 10;

-- hash join
SELECT /*+  use_hash(d) */ *
FROM EMP e, DEPT d
WHERE e.DEPTNO = d.DEPTNO AND e.DEPTNO = 10;